# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14f0a3a3b0801974b2ea447f2b0868aea3c4f062e683f77c65028b8f24164678b1c45d4d867814647ed9fac2b0cbbf05b4695f629ba805038e32130e4a877b34

test:
  secret_key_base: ca1b757da31441d60087f8f285e1ed1487f29b92e8a1f1a681eb7d09ee8da6c10e98776204d43b04a5a63a9449031115d522a45eb1f405d9fe57e6172ac9dae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
